// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onOcupacaoChange();
void onBuiltInLEDChange();

int ocupacao;
bool builtInLED;

void initProperties(){

  ArduinoCloud.addProperty(ocupacao, READWRITE, ON_CHANGE, onOcupacaoChange);
  ArduinoCloud.addProperty(builtInLED, READWRITE, ON_CHANGE, onBuiltInLEDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
